In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [6]:
data_folder = "F:/data-extract/ant-bee/train"

In [8]:
# Create a dataset.
dataset_train = keras.preprocessing.image_dataset_from_directory(data_folder, batch_size=32, image_size=(244, 244))

Found 245 files belonging to 2 classes.


In [11]:
len(dataset_train)

8

In [13]:
dataset_train

<BatchDataset shapes: ((None, 244, 244, 3), (None,)), types: (tf.float32, tf.int32)>

In [19]:
for data, labels in dataset_train:
   #print(data.shape)  # (64, 200, 200, 3)
   #print(data.dtype)  # float32
   #print(labels.shape)  # (64,)
   #print(labels.dtype)  # int32
   print(labels)

tf.Tensor([1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1], shape=(32,), dtype=int32)
tf.Tensor([0 0 1 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0], shape=(32,), dtype=int32)
tf.Tensor([0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 0 0 1 1 1], shape=(32,), dtype=int32)
tf.Tensor([0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0], shape=(32,), dtype=int32)
tf.Tensor([0 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0], shape=(32,), dtype=int32)
tf.Tensor([0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 0 1 0], shape=(32,), dtype=int32)
tf.Tensor([1 0 1 0 0 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 0 1 1 0 1 1 0], shape=(32,), dtype=int32)
tf.Tensor([0 1 1 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 1], shape=(21,), dtype=int32)
